version: '3.3'
services:
  confluence:
    image: atlassian/confluence-server:ubuntu-18.04-adoptopenjdk8
    ports:
      - "8090:8090"
      - "8091:8091"
    restart: always
    volumes:
      - confluence:/var/atlassian/application-data/confluence
volumes:
  confluence:
